### ISSUE TITLE
about 'animation' was deprecated in iOS 15.0

### ISSUE THREAD

**Issue by nuovotaka** [SwiftfulThinking/SwiftUI-Crypto-MVVM-CoreData-Combine#2]
'animation' was deprecated in iOS 15.0: Use withAnimation or animation(_:value:) instead.

**Comment by PinYuanChen** [comment]
I found this [article](https://www.avanderlee.com/swiftui/disable-animations-transactions/) and I followed the instruction used 
```
.transaction { transaction in
   transaction.animation = nil
}
```
This looks good to me.
